### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by matudelatower** [ckfinder/ckfinder-symfony-bundle#26]
- add support Symfony 5.

to change upload folder i.e. to `packages/ckfinder.yaml`: 

```yaml
ckfinder:
  connector:
    authenticationClass: App\CustomCKFinderAuth\CustomCKFinderAuth
    backends:
      default:
        name: default
        baseUrl: '%app.path.novedad_files%/'
        root: '%kernel.project_dir%/public%app.path.novedad_files%'
```
