### ISSUE TITLE
[Feature Request] Allow to re-use an already existing S3Client instance

### ISSUE THREAD

**Issue by Kocal** [ckfinder/ckfinder-symfony-bundle#46]
Hi!

First, thank you for taking over the maintenance of this bundle, we all thought it was abandoned and would prevent us to migrate to Symfony 6 (due to dependencies issues between `symfony/cache` and `league/cached-adapter` IIRC). 
This is why I've [forked the projet](https://github.com/Kocal/ckfinder-symfony-bundle) and added many features (patches, taking a `S3Client` instance from the Container, using a PSR-6 cache pool, PHPStan, ...), and used it in our application.

So, in the futur we plan to drop my fork and re-use this bundle, but before that we need to find a way to prevent the `BackendFactory` to create a `S3Client` by itself, and use a `S3Client` instance from the Symfony Container. 

I implemented this feature in https://github.com/Kocal/ckfinder-symfony-bundle/pull/17 and https://github.com/Kocal/ckfinder-symfony-bundle/pull/19, but I'm not super proud of it because I think it can be done in a better way. 

# Implementations idea

## 1. Configuration in the bundle 

Ideally, we want to configure it at the `backend` configuration level, with a key `client` that will take a string representing a service identifier.

```yaml
services:
    aws_s3_client:
        class: Aws\S3\S3Client
        arguments:
            - version: 'latest'
              region: '%aws_s3_region%'
              credentials:
                  key: '%aws_s3_client_key%'
                  secret: '%aws_s3_client_secret%'	
              # more options [...]

ckfinder:
  connector:
    backends:
      aws:
        name: 'aws'
        adapter: 's3'
        bucket: '%aws_s3_bucket%'
        client: 'aws_s3_client' // or `@aws_s3_client`
```

## 2. Dealing with the `BackendFactory`

Then we need to pass this `S3Client` instance to the `BackendFactory`. 

In my fork, I've used a `ServiceLocator`: 
- that is injected to the `ConnectorFactory`: https://github.com/Kocal/ckfinder-symfony-bundle/blob/main/src/DependencyInjection/CKSourceCKFinderExtension.php#L95-L97 and https://github.com/Kocal/ckfinder-symfony-bundle/blob/main/src/Factory/ConnectorFactory.php#L32
- that is used in the patched `BackendFactory`, see https://github.com/Kocal/ckfinder-symfony-bundle/blob/main/src/Patcher/BackendAwsS3ClientPatcher.php#L35

But it means that `BackendFactory` from the CKFinder PHP Connector should be updated on your side, since I don't think we want to re-introduce a patching system here.

---

Do you think this would be possible? Injecting a service reference in bundles in pretty common, e.g. with The PHP League's Flysystem bundle:
```yaml
flysystem:
    storages:
        cloud.storage.aws_s3:
            adapter: 'aws'
			# ...
            options:
                client: 'aws_s3_client' # <-- here
                bucket: '%aws_s3_bucket%'
```

or with LiipImagineBundle: 
```yaml
    app.imagine.cache.resolver.aws_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - '@aws_s3_client' # <-- here
            - '%aws_s3_bucket%'
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'aws_s3' }
```

Thanks!
